### ISSUE TITLE
Include helm to container

### ISSUE THREAD

**Issue by werwolfby** [line/kubectl-kustomize#14]
I use `kustomize` with helm.

So it would be nice to add it to the container. I've created my form with it.

And I'm not sure should I create a PR for this or not?

Do you want to have a `helm` inside this container? Or this would requires a new one docker image like I did: [`werwolfby/kubectl-kustomize-helm`](https://hub.docker.com/r/werwolfby/kubectl-kustomize-helm)?

**Comment by heojay** [comment]
Hello, @werwolfby 

I believe it may not be appropriate to support Helm in this image. As you mentioned, it would be better to use a different image for that purpose. However, I appreciate your good suggestion.

Thank you.
