### ISSUE TITLE
Remove 'sh' entrypoint

### ISSUE THREAD

**Issue by flyte** [line/kubectl-kustomize#9]
Hi, I'm trying to use your image on GitLab CI, but where you've overridden the base Alpine image's entrypoint, it causes the job to fail. I believe it's because GitLab tries to use the CMD of `sh` itself:

```
sh: can't open 'sh': No such file or directory
```

The fix, I believe, is to just remove the ENTRYPOINT line from your Dockerfile entirely, and use the standard Alpine one, which works fine.

**Comment by devholic** [comment]
Hello [@flyte](https://github.com/flyte),
I'm not sure about which runner you use, but [overriding entrypoint seems possible in the Docker runner](https://docs.gitlab.com/ee/ci/docker/using_docker_images.html#overriding-the-entrypoint-of-an-image).

Could you try to override the entrypoint with a blank string like `entrypoint: [""]`?
Reference - https://gitlab.com/gitlab-org/gitlab-runner/-/issues/1421

**Comment by flyte** [comment]
I don't have control of the endpoint that Gitlab uses (I don't think) but
to be honest you probably want to remove that line anyway and stick with
the default Alpine one which does the same thing as you're intending with
this one, but works universally (try it!).

**Comment by devholic** [comment]
@flyte Will be applied from next release 🙂

**Comment by flyte** [comment]
Thank you!
